all:	location_updater calendar_filter email_filter

prog1: prog1.c
	gcc -o location_updater location_updater.c
prog2: prog2.c
	gcc -o calendar_filter calendar_filter.c
prog3: prog3.c
	gcc -o email_filter email_filter.c
clean:
	rm -rf location_updater calendar_filter email_filter
